Fix _dir variable
ros-melodic-arch/ros-melodic-mk pull request #1
Opened 2020-05-18 09:08 UTC by liborw

Will not build like this, probably new structure of the ros repository:

```
==> Retrieving sources...
  -> Found ros-melodic-mk-1.14.8.tar.gz
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Extracting ros-melodic-mk-1.14.8.tar.gz with bsdtar
==> Starting build()...
grep: /build/ros-melodic-mk/src/ros-1.14.8/mk: No such file or directory
CMake Error: The source directory "/build/ros-melodic-mk/src/ros-1.14.8/mk" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
==> ERROR: A failure occurred in build().
    Aborting...
```

2020-05-20 21:46 UTC, acxz requested changes
Make sure to bump pkgrel up 1 when updating a package. See: https://wiki.archlinux.org/index.php/PKGBUILD#pkgrel
Also don't forget to update .SRCINFO as well See: https://wiki.archlinux.org/index.php/.SRCINFO

2020-05-21 07:12 UTC, liborw commented
As the package would not build i guess that there is no need for new pkgrel?

2020-05-21 08:05 UTC, acxz commented
If we do not update the pkgrel then the AUR will not know the PKGBUILD has been updated and it will still host the older broken PKGBUILD.

2020-05-21 08:36 UTC, acxz approved these changes
thx!

2020-05-21 08:40 UTC, liborw commented
Ok, fixed for all the other PRs, there are more similar problems, basically all packages from ros, ros_comm, moveit... i guess that there is some script to update the package which does not take in account the sub directories, i can make PRs for all if it would help, but probably it would be better to fix that script?

Didn't know where to put it, is the some ros-arch wide discussion?

2020-05-21 08:42 UTC, acxz commented
For the general ros-arch wide discussion we just open up corresponding issues on the https://github.com/ros-melodic-arch/ros-melodic-desktop-full repo

2020-05-21 08:47 UTC, merged

2020-05-21 08:48 UTC, acxz commented
yeah seems to be the case, I'll ping @bionade24  here just in case